### ISSUE TITLE
Does not work since the update from 2023.10.5 to 2023.11.0b0

### ISSUE THREAD

**Issue by TonyOneZero** [tronikos/google_assistant_sdk_custom#13]
Does not work since the update from 2023.10.5 to 2023.11.0b0

ErrorLog:

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 09:32:13 (1 occurrences)
Last logged: 09:32:13

Setup failed for custom integration google_assistant_sdk_custom: Unable to import component: cannot import name 'SERVICE_HOMEASSISTANT_RESTART' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/google_assistant_sdk_custom/__init__.py", line 11, in <module>
    from homeassistant.const import SERVICE_HOMEASSISTANT_RESTART
ImportError: cannot import name 'SERVICE_HOMEASSISTANT_RESTART' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```
It looks like the service "SERVICE_HOMEASSISTANT_RESTART" has been moved from the /homeassistant/const.py to the /homeassistant/components/homeassistant/const.py. This most likely triggers the error.

Source:
https://github.com/home-assistant/core/compare/2023.10.5...2023.11.0b0?diff=split#diff-902818bfbf29bed3a8f93d3514499e76921cc8c8798431e0a64b7f5077ec0e80
https://github.com/home-assistant/core/compare/2023.10.5...2023.11.0b0?diff=split#diff-07e20eb7c6560330f9774eb23343f5dd3002106bb8b6523ccb18d95857990d77

**Comment by tronikos** [comment]
Fixed with https://github.com/tronikos/google_assistant_sdk_custom/releases/tag/v0.1.0
